"""initial schema: JobPosting, Application, Skill, JobPostingSkill, AnalysisRun

Revision ID: 1d7cc5ae1dfc
Revises: 
Create Date: 2026-08-30 16:47:24.616696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d7cc5ae1dfc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_postings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=180), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_postings_content_hash'), 'job_postings', ['content_hash'], unique=True)
    op.create_index(op.f('ix_job_postings_id'), 'job_postings', ['id'], unique=False)
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_name', sa.String(length=80), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=False),
    sa.Column('group', sa.String(length=60), nullable=False),
    sa.Column('is_ambiguous', sa.Boolean(), nullable=False),
    sa.Column('requires_case_sensitive', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_canonical_name'), 'skills', ['canonical_name'], unique=True)
    op.create_index(op.f('ix_skills_id'), 'skills', ['id'], unique=False)
    op.create_table('analysis_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_posting_id', sa.Integer(), nullable=False),
    sa.Column('extractor_type', sa.String(length=20), nullable=False),
    sa.Column('extractor_version', sa.String(length=20), nullable=False),
    sa.Column('model_name', sa.String(length=60), nullable=True),
    sa.Column('structured_result', sa.JSON(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['job_posting_id'], ['job_postings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_runs_id'), 'analysis_runs', ['id'], unique=False)
    op.create_table('job_posting_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_posting_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('requirement_level', sa.Enum('REQUIRED', 'PREFERRED', 'MENTIONED', name='requirementlevel'), nullable=False),
    sa.Column('evidence_span', sa.Text(), nullable=True),
    sa.Column('extractor_source', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['job_posting_id'], ['job_postings.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_posting_id', 'skill_id', 'extractor_source', name='uq_posting_skill_extractor')
    )
    op.create_index(op.f('ix_job_posting_skills_id'), 'job_posting_skills', ['id'], unique=False)
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_posting_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('SAVED', 'APPLIED', 'INTERVIEWING', 'OFFER', 'REJECTED', 'WITHDRAWN', name='applicationstatus'), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('date_applied', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['job_posting_id'], ['job_postings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_id'), 'applications', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_applications_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_job_posting_skills_id'), table_name='job_posting_skills')
    op.drop_table('job_posting_skills')
    op.drop_index(op.f('ix_analysis_runs_id'), table_name='analysis_runs')
    op.drop_table('analysis_runs')
    op.drop_index(op.f('ix_skills_id'), table_name='skills')
    op.drop_index(op.f('ix_skills_canonical_name'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_job_postings_id'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_content_hash'), table_name='job_postings')
    op.drop_table('job_postings')
    # ### end Alembic commands ###
